(source gnu)
(source melpa)

(depends-on "smex")
(depends-on "paredit")
(depends-on "clojure-mode")
(depends-on "projectile")
(depends-on "rainbow-delimiters")
(depends-on "idle-highlight-mode")
(depends-on "flx-ido")
(depends-on "cider")
(depends-on "ag")
(depends-on "ac-cider")
(depends-on "tabbar")
(depends-on "imenu-anywhere")
(depends-on "command-log-mode")