(source gnu)
(source melpa)

(depends-on "smex")
(depends-on "paredit")
(depends-on "clojure-mode")
(depends-on "projectile")
(depends-on "rainbow-delimiters")
(depends-on "idle-highlight-mode")
(depends-on "ido-ubiquitous")
(depends-on "flx-ido")
(depends-on "cider")
(depends-on "company")
(depends-on "ag")
(depends-on "clj-refactor")