(source gnu)
(source melpa)
(source marmalade)

(depends-on "smex")
(depends-on "paredit")
(depends-on "clojure-mode")
(depends-on "projectile")
(depends-on "rainbow-delimiters")
(depends-on "idle-highlight-mode")
(depends-on "flx-ido")
(depends-on "cider")
(depends-on "ag")
(depends-on "ac-cider")
(depends-on "tabbar")
(depends-on "imenu-anywhere")
(depends-on "command-log-mode")
(depends-on "highlight-parentheses")
(depends-on "swift-mode")
(depends-on "android-mode")
(depends-on "flycheck-clojure")
(depends-on "flycheck-pos-tip")
(depends-on "pbcopy")
(depends-on "lispy")
(depends-on "json-mode")
(depends-on "clj-refactor" "1.1.0")